### ISSUE TITLE
Confused about importance weights

### ISSUE THREAD

**Issue by junkangwu** [kyungmnlee/RenyiCL#1]
Hi, Kyungmin
     Nice work !! It provide a unified framework for me to understand contrastive learning. However, I am confused about its implementation. In your code of  Pseudocode, RenyiCL leverage a importance weights to each instances. Is is consistent with the definition of RMLCPC objective? Looking forward to your reply. Thanks!
Best,

**Comment by kyungmnlee** [comment]
Hi Junkang
Thank you for your interest on our work! In our manuscript, we derive that RMLCPC leverages pairwise importance weight by looking into the gradient. Then in our implementation, RényiCL uses RMLCPC objective with importance-weighted form.

If you have any questions, let us know
Thank you

**Comment by junkangwu** [comment]
Thanks for your reply. I get it!
Best
